# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

# aliases
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi
# aliases end

# aliases pfx
if [ -f ~/.bash_pfx ]; then
	. ~/.bash_pfx
fi
# aliases pfx end

unset rc

# node
export NODE_HOME="$HOME/.app/node/bin"
case ":$PATH:" in
  *":$NODE_HOME:"*) ;;
  *) export PATH="$NODE_HOME:$PATH" ;;
esac
# node end

# node_modules
export NODE_MODULES_HOME="$HOME/.npm-global/bin"
case ":$PATH:" in
  *":$NODE_MODULES_HOME:"*) ;;
  *) export PATH="$NODE_MODULES_HOME:$PATH" ;;
esac
# node_modules end

# pnpm
export PNPM_HOME="/home/donataskartanovicius/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
